In [2]:
import pandas as pd

In [3]:
df = pd.read_excel(r"C:\Users\INDIA\OneDrive\Desktop\cricket_t20.xlsx")
print(df.head())
print(df.tail())

   match_id  match_date  season format team1 team2         venue       city  \
0         1  2023-01-03    2025    T20    DC   KKR  Arun Jaitley    Chennai
1         2  2023-01-04    2024    T20  PBKS   CSK  Arun Jaitley  Ahmedabad
2         3  2023-01-05    2026    T20  PBKS   RCB      Wankhede  Bengaluru
3         4  2023-01-06    2023    T20    MI    RR       Chepauk    Kolkata
4         5  2023-01-07    2026    T20   SRH   CSK       Chepauk  Ahmedabad

  country toss_winner  ... win_margin result_type powerplay_runs  \
0   India          DC  ...       Runs          61             73
1   India         CSK  ...       Runs          80             76
2   India        PBKS  ...    Wickets          65            100
3   India          RR  ...    Wickets          32             80
4   India         CSK  ...    Wickets          32            109

   middle_overs_runs  death_overs_runs  sixes  fours  extras total_score  \
0                 45                25     46      0     406       58685
1                 63                14     19      6     363       92141
2                 45                 8     44     13     443       18858
3                 71                 7     25     15     383       29224
4                 70                17     26      0     438       56881

   attendance
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN

[5 rows x 30 columns]
     match_id  match_date  season format team1 team2         venue       city  \
495       496  2024-05-12    2026    T20   LSG    DC  Eden Gardens     Mumbai
496       497  2024-05-13    2025    T20   SRH  PBKS       Chepauk    Chennai
497       498  2024-05-14    2025    T20    DC   RCB      Wankhede  Bengaluru
498       499  2024-05-15    2026    T20    MI   KKR  Eden Gardens    Kolkata
499       500  2024-05-16    2025    T20  PBKS    MI  Arun Jaitley    Kolkata

    country toss_winner  ... win_margin result_type powerplay_runs  \
495   India          DC  ...       Runs          52             87
496   India         SRH  ...       Runs          65             76
497   India          DC  ...    Wickets          38             40
498   India         KKR  ...       Runs          40             55
499   India        PBKS  ...       Runs          56             60

     middle_overs_runs  death_overs_runs  sixes  fours  extras total_score  \
495                 23                 6     39      0     277       35707
496                 78                25     31     13     313       47565
497                 44                21     33     15     336       43548
498                 61                 6     32     17     361       23171
499                 40                21     13      7     336       35465

     attendance
495         NaN
496         NaN
497         NaN
498         NaN
499         NaN

[5 rows x 30 columns]

In [4]:
#Data Cleaning
df.drop_duplicates(inplace=True)
df.isnull().sum()

match_id               0
match_date             0
season                 0
format                 0
team1                  0
team2                  0
venue                  0
city                   0
country                0
toss_winner            0
toss_decision          0
player_of_match        0
captain_team1          0
captain_team2          0
team1_score            0
team2_score            0
runs_scored            0
wickets_taken          0
overs_played           0
winner                 0
win_margin             0
result_type            0
powerplay_runs         0
middle_overs_runs      0
death_overs_runs       0
sixes                  0
fours                  0
extras                 0
total_score            0
attendance           500
dtype: int64

In [5]:
# total matches

total_matches = df['match_id'].nunique()
print(total_matches)

500

In [6]:
#Total Runs

total_runs = df['runs_scored'].sum()
print(total_runs)

2300

In [7]:
#Total Wickets

total_wickets = df['wickets_taken'].sum()
print(total_wickets)

10000

In [8]:
#Total Venues

total_venues = df['venue'].nunique()
print(total_venues)

# top 10 vanues

df['venue'].value_counts().head(10)

6

venue
Chinnaswamy              96
Chepauk                  90
Wankhede                 88
Arun Jaitley             86
Eden Gardens             71
Narendra Modi Stadium    69
Name: count, dtype: int64

In [9]:
#Team Wise Runs

df.groupby('winner')['runs_scored'].sum()

winner
0      27
1      14
2      57
3      12
4      58
       ..
118    10
119    19
121     7
122     4
125     0
Name: runs_scored, Length: 112, dtype: int64

In [10]:
#Team Wise Matches Won
df.groupby('winner').size()

winner
0       4
1       5
2      11
3       3
4      13
       ..
118     1
119     2
121     2
122     1
125     1
Length: 112, dtype: int64

In [11]:
df.groupby('venue').size()

venue
Arun Jaitley             86
Chepauk                  90
Chinnaswamy              96
Eden Gardens             71
Narendra Modi Stadium    69
Wankhede                 88
dtype: int64

In [12]:
df.sort_values('runs_scored', ascending=False)

,match_id,match_date,season,format,team1,team2,venue,city,country,toss_winner,...,win_margin,result_type,powerplay_runs,middle_overs_runs,death_overs_runs,sixes,fours,extras,total_score,attendance
0,1,2023-01-03,2025,T20,DC,KKR,Arun Jaitley,Chennai,India,DC,...,Runs,61,73,45,25,46,0,406,58685,NaN
28,29,2023-01-31,2026,T20,PBKS,RCB,Wankhede,Bengaluru,India,RCB,...,Wickets,44,93,80,18,20,2,460,68933,NaN
43,44,2023-02-15,2023,T20,KKR,SRH,Chepauk,Mumbai,India,KKR,...,Runs,78,46,48,23,14,5,380,73342,NaN
44,45,2023-02-16,2025,T20,RR,MI,Chepauk,Delhi,India,MI,...,Wickets,49,117,36,19,22,5,325,16468,NaN
54,55,2023-02-26,2025,T20,KKR,SRH,Arun Jaitley,Bengaluru,India,KKR,...,Wickets,41,80,43,23,17,0,376,85735,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,307,2023-11-05,2025,T20,KKR,LSG,Wankhede,Bengaluru,India,LSG,...,Wickets,76,92,67,5,43,5,429,78729,NaN
82,83,2023-03-26,2024,T20,KKR,MI,Narendra Modi Stadium,Kolkata,India,MI,...,Runs,40,69,76,25,16,6,324,91325,NaN
463,464,2024-04-10,2025,T20,DC,RR,Chepauk,Ahmedabad,India,DC,...,Wickets,38,74,63,13,24,4,289,93676,NaN
344,345,2023-12-13,2025,T20,KKR,RR,Chepauk,Delhi,India,KKR,...,Wickets,59,106,22,11,40,15,352,32636,NaN
499,500,2024-05-16,2025,T20,PBKS,MI,Arun Jaitley,Kolkata,India,PBKS,...,Runs,56,60,40,21,13,7,336,35465,NaN

In [23]:
# Filtering
df[df['season'] == 2023]
df[df['runs_scored'] < 123]
df[(df['season']==2023) & (df['runs_scored']<180)]

,match_id,match_date,season,format,team1,team2,venue,city,country,toss_winner,...,win_margin,result_type,powerplay_runs,middle_overs_runs,death_overs_runs,sixes,fours,extras,total_score,attendance
3,4,2023-01-06,2023,T20,MI,RR,Chepauk,Kolkata,India,RR,...,Wickets,32,80,71,7,25,15,383,29224,NaN
10,11,2023-01-13,2023,T20,RR,PBKS,Wankhede,Delhi,India,RR,...,Runs,64,111,71,13,15,19,320,90230,NaN
21,22,2023-01-24,2023,T20,GT,SRH,Arun Jaitley,Ahmedabad,India,SRH,...,Runs,52,94,51,14,22,8,441,88576,NaN
22,23,2023-01-25,2023,T20,RR,KKR,Arun Jaitley,Delhi,India,RR,...,Wickets,43,90,31,14,31,15,346,88991,NaN
24,25,2023-01-27,2023,T20,CSK,GT,Wankhede,Bengaluru,India,GT,...,Wickets,39,96,40,25,24,6,408,65814,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,481,2024-04-27,2023,T20,LSG,MI,Arun Jaitley,Delhi,India,MI,...,Wickets,66,48,69,22,44,12,456,97919,NaN
483,484,2024-04-30,2023,T20,LSG,GT,Arun Jaitley,Ahmedabad,India,LSG,...,Wickets,77,48,55,2,34,6,320,87541,NaN
485,486,2024-05-02,2023,T20,LSG,DC,Eden Gardens,Delhi,India,DC,...,Runs,60,112,23,4,42,0,328,47108,NaN
487,488,2024-05-04,2023,T20,PBKS,DC,Chepauk,Delhi,India,PBKS,...,Wickets,64,115,78,4,20,6,444,27212,NaN
490,491,2024-05-07,2023,T20,MI,CSK,Wankhede,Ahmedabad,India,MI,...,Runs,64,81,53,9,17,3,375,20295,NaN

In [27]:
#Top 5 Teams by Runs
df.groupby('winner')['runs_scored'].sum().nlargest(5)

winner
28    86
30    67
22    63
4     58
2     57
Name: runs_scored, dtype: int64

In [28]:



pd.unique(pd.concat([df['team1'], df['team2']]))

array(['DC', 'PBKS', 'MI', 'SRH', 'GT', 'RR', 'KKR', 'LSG', 'CSK', 'RCB'],
      dtype=object)

In [26]:
#Top 10 Venues
df['venue'].value_counts().head(10)

venue
Chinnaswamy              96
Chepauk                  90
Wankhede                 88
Arun Jaitley             86
Eden Gardens             71
Narendra Modi Stadium    69
Name: count, dtype: int64

In [21]:
#Season vs Runs  (pivot table)
pd.pivot_table(
    df,
    values='runs_scored',
    index='season',
    aggfunc='sum'
)

        runs_scored
season
2023            622
2024            489
2025            648
2026            541